export const staticPaths = {
  home: "/",
  login: "/login",
  register: "/register",
  forgot_password: "/forgot-password",
  reset_password: "/reset-password",
  create_user_name: "/create-username",
  about_us: "/about-us",
  achievements: (username_slug: string) => `/achievements/${username_slug}`,
  article: "/article",
  article_category: "/article/category",
  article_category_detail: (category_slug: string) =>
    `/article/category/${category_slug}`,
  article_detail: (article_slug: string) => `/article/${article_slug}`,
  game_category: "/game-category",
  game_category_all: "/game-category-all",
  game_screen: "/game-screen",
  hall_of_fame: "/hall-of-fame",
  privacy_policy: "/privacy-policy",
  simple_shop: "/simple-shop",
  terms_of_use: "/terms-of-use",
  user: "/user",
  maintenance: "/maintenance",
  not_found: "/not-found",
};
