export const staticPaths = {
  home: "/",
  login: "/login",
  register: "/register",
  forgot_password: "/forgot-password",
  reset_password: "/reset-password",
  create_user_name: "/create-username",
  about_us: "/about-us",
  achievements: "/achievements",
  article_category_all: "/article-category-all",
  game_category: "/game-category",
  game_category_all: "/game-category-all",
  game_screen: "/game-screen",
  my_hall_of_fame: "/game/hall-of-fame",
  news: "/news",
  privacy_policy: "/privacy-policy",
  simple_shop: "/simple-shop",
  terms_of_use: "/terms-of-use",
  user: "/user",
  maintenance: "/maintenance",
  not_found: "/not-found",
};
